# Generated by Django 4.0.4 on 2022-05-07 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwproject',
            name='date_added',
            field=models.TimeField(default=datetime.datetime(2022, 5, 7, 12, 46, 3, 630473)),
        ),
    ]
