# Generated by Django 4.0.4 on 2022-08-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gwproject_date_added'),
    ]

    operations = [
        migrations.RenameModel('GWProject', 'Project')
    ]
